name: Hardcore
version: '${version}'
main: me.ancliz.hardcore.Hardcore
api-version: '1.20'
author: Ancliz
website: https://github.com/ancliz-mc/hardcore
softdepend: [EssentialsX]


commands:
  hardcore:
    description: Hardcore related commands. Type /hardcore help for a full list.
    permission: hardcore.administrator
    aliases:
     - hc